Dev2
Deveeeers/service_split pull request #7
Opened 2024-07-08 10:42 UTC by howabsurd

2024-07-08 19:59 UTC, mahavirgoyal32 requested changes

2024-07-08 19:59 UTC, mahavirgoyal32 commented on src/db/migrations/20240629042334-add-table-groupDetail.cjs
make group_id to id it is better

2024-07-09 04:59 UTC, howabsurd commented on src/db/migrations/20240629042334-add-table-groupDetail.cjs
Changed the tables

2024-07-09 14:43 UTC, mahavirgoyal32 commented on src/service/group/add.js
its better to make add, delete edit fucntions in different files and export through index.js

2024-07-09 14:48 UTC, mahavirgoyal32 requested changes

2024-07-09 14:48 UTC, mahavirgoyal32 commented on src/repository/groupRepository.js
> +    const newGroup = await Model.GroupDetail.create(data.body, options);
directly do this 
const newGroup = await Model.GroupDetail.create(data, options);
and no need to handle internal server error here 
handle only this in services catch and throw internal server error from there

2024-07-09 16:40 UTC, merged